In [ ]:
Introduction to Numpy:

In [ ]:
installation of numpy: 

In [1]:
!pip install numpy

In [15]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in c:\users\lenovo\anaconda3\lib\site-packages (1.19.2)


In [27]:
import numpy as np 

In [ ]:
understanding the datatype of numpy:
    array---> datatype which numpy provideas
    ndarray----> N dimentional arrays.

In [30]:
array_one = np.array([1,2,3,4])

In [31]:
array_one

array([1, 2, 3, 4])

In [32]:
type(array_one)

numpy.ndarray

In [34]:
numbers = [7,8,9,3]

In [35]:
array_two = np.array(numbers)

In [36]:
array_two

array([7, 8, 9, 3])

In [37]:
type(array_two)

numpy.ndarray

In [38]:
array_of_zeros = np.zeros([3,4])

In [39]:
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
array_of_ones = np.ones([3,4])

In [44]:
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
req: eliminate the dots or the decimals:

In [47]:
array_of_ones_int = np.ones([3,4], dtype=np.int16)

In [48]:
array_of_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [ ]:
|