In [3]:
import numpy as np

In [ ]:
req: implimenting and identify matrix

In [5]:
array_eye = np.eye(4)

array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
array_eye = np.eye(6)
array_eye

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
req: i want to print the number between 0,20 by using numpy

In [19]:
array_two = np.arange(0,20)

array_two

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
req: array of even number 2 to 30 i want to print this:

In [21]:
array_of_evens = np.arange(2,30,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [23]:
array_of_odds = np.arange(3,30,3)
array_of_odds

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
req: to have a range of numbers till 8

In [25]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [26]:
x.shape

(8,)

In [ ]:
2d array:

In [27]:
array_nd = x.reshape(2,4)

In [28]:
array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [29]:
array_nd.shape

(2, 4)

In [30]:
x = np.arange(12)

In [31]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
array_nd = x.reshape(2,6)

In [35]:
array_nd

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])